import Anthropic from "@anthropic-ai/sdk";
import fs from "fs/promises";
import path from "path";
import type { Automation, ClientConfig, DashboardKpis } from "./types";

interface ReportInput {
  clientId: string;
  config: ClientConfig;
  kpis: DashboardKpis;
  automations: Automation[];
  month: string;
  year: number;
}

export async function generateMonthlyReport(
  input: ReportInput
): Promise<{ filename: string; content: string }> {
  const { clientId, config, kpis, automations, month, year } = input;
  const slug = month.toLowerCase();
  const filename = `${clientId}-${slug}-${year}.pdf`;

  const apiKey = process.env.ANTHROPIC_API_KEY;
  let summary = buildStubSummary(config, kpis, automations, month, year);

  if (apiKey) {
    try {
      const client = new Anthropic({ apiKey });
      const response = await client.messages.create({
        model: "claude-sonnet-4-20250514",
        max_tokens: 1024,
        messages: [
          {
            role: "user",
            content: `Write a concise executive summary (3-4 paragraphs) for a monthly AI automation report for ${config.clientName}. Month: ${month} ${year}. KPIs: ${JSON.stringify(kpis)}. Automations: ${automations.map((a) => `${a.name} (${a.status}, ${a.successRate}% success)`).join(", ")}. Professional tone, results-focused.`,
          },
        ],
      });

      const textBlock = response.content.find((b) => b.type === "text");
      if (textBlock && textBlock.type === "text") {
        summary = textBlock.text;
      }
    } catch {
      // Fall back to stub summary
    }
  }

  const pdfContent = buildSimplePdf(config.clientName, month, year, summary);
  const reportsDir = path.join(
    process.cwd(),
    "data",
    "clients",
    clientId,
    "reports"
  );
  await fs.mkdir(reportsDir, { recursive: true });
  await fs.writeFile(path.join(reportsDir, filename), pdfContent);

  return { filename, content: summary };
}

function buildStubSummary(
  config: ClientConfig,
  kpis: DashboardKpis,
  automations: Automation[],
  month: string,
  year: number
): string {
  const running = automations.filter((a) => a.status === "running").length;
  const errors = automations.filter((a) => a.status === "error").length;

  return `${config.clientName} — ${month} ${year} Automation Report

This month, your AI automations processed ${kpis.tasksAutomated.toLocaleString()} tasks, saving an estimated ${kpis.hoursSaved} staff hours. Your ROI estimate stands at $${kpis.roiEstimate.toLocaleString()} based on time savings and reduced manual processing.

${running} automations are currently running smoothly. ${errors > 0 ? `${errors} automation(s) require attention — please review the dashboard for error details.` : "All systems are operating within normal parameters."}

Key highlights include continued strong performance from appointment reminders (${automations.find((a) => a.id === "auto-reminders")?.successRate ?? "N/A"}% success rate) and patient intake processing. We recommend scheduling a review call if any automations remain in error status.

Generated by Clinovyr Intelligence, Applied.`;
}

function buildSimplePdf(
  clientName: string,
  month: string,
  year: number,
  body: string
): Buffer {
  const title = `${clientName} — ${month} ${year} Report`;
  const lines = body.split("\n").slice(0, 20);
  const textOps = lines
    .map((line, i) => {
      const escaped = line.replace(/[()\\]/g, "\\$&").slice(0, 80);
      return `BT /F1 11 Tf 50 ${750 - i * 16} Td (${escaped}) Tj ET`;
    })
    .join("\n");

  const stream = `${textOps}\nBT /F1 18 Tf 50 770 Td (${title.replace(/[()\\]/g, "\\$&")}) Tj ET`;
  const streamLen = stream.length;

  const pdf = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/MediaBox[0 0 612 792]/Parent 2 0 R/Contents 4 0 R/Resources<</Font<</F1 5 0 R>>>>>>endobj
4 0 obj<</Length ${streamLen}>>stream
${stream}
endstream endobj
5 0 obj<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>endobj
xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000240 00000 n 
0000000${(300 + streamLen).toString().padStart(3, "0")} 00000 n 
trailer<</Size 6/Root 1 0 R>>
startxref
${350 + streamLen}
%%EOF`;

  return Buffer.from(pdf, "utf-8");
}
