import * as fs from "fs";
import * as path from "path";
import * as readline from "readline";
import {
  ClientConfig,
  CustomizeResult,
  slugifyCompanyName,
  SubstitutionRecord,
  TemplateLibrary,
} from "./template-manager";

interface WizardAnswers {
  templateIds: string[];
  companyName: string;
  crmType: string;
  emailProvider: string;
  webhookUrl: string;
  apiKeys: Record<string, string>;
}

function createReadlineInterface(): readline.Interface {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
}

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer: string) => resolve(answer.trim()));
  });
}

function parseTemplateSelection(
  input: string,
  templates: ReturnType<TemplateLibrary["listTemplates"]>
): string[] {
  const trimmed = input.trim();

  if (!trimmed) {
    return [];
  }

  const tokens = trimmed.split(/[\s,]+/).filter(Boolean);
  const selected = new Set<string>();

  for (const token of tokens) {
    const asNumber = Number.parseInt(token, 10);

    if (!Number.isNaN(asNumber) && asNumber >= 1 && asNumber <= templates.length) {
      selected.add(templates[asNumber - 1].id);
      continue;
    }

    const byId = templates.find((template) => template.id === token);
    if (byId) {
      selected.add(byId.id);
      continue;
    }

    throw new Error(`Invalid template selection: "${token}"`);
  }

  return Array.from(selected);
}

async function promptApiKeys(rl: readline.Interface): Promise<Record<string, string>> {
  const apiKeys: Record<string, string> = {};
  const addMore = await ask(
    rl,
    "Add optional API keys? (y/N): "
  );

  if (!/^y(es)?$/i.test(addMore)) {
    return apiKeys;
  }

  console.log(
    "Enter API keys one at a time. Use keys like OPENAI, TWILIO, or CRM (stored as {{API_KEY_*}})."
  );

  while (true) {
    const keyName = await ask(rl, "API key name (blank to finish): ");
    if (!keyName) {
      break;
    }

    const keyValue = await ask(rl, `Value for API_KEY_${keyName.toUpperCase()}: `);
    if (!keyValue) {
      console.log("Skipping empty value.");
      continue;
    }

    apiKeys[keyName.toUpperCase()] = keyValue;
  }

  return apiKeys;
}

function buildReadme(
  companyName: string,
  templateIds: string[],
  library: TemplateLibrary
): string {
  const templateLines = templateIds
    .map((id) => {
      const template = library.getTemplate(id);
      return `- **${template.name}** (\`${id}\`) — ${template.description}`;
    })
    .join("\n");

  return `# Make.com Automations for ${companyName}

Generated by the Clinovyr Make.com template wizard.

## Included templates

${templateLines}

## Import instructions (Make.com)

1. Log in to [Make.com](https://www.make.com/) and open your organization.
2. Go to **Scenarios** → **Create a new scenario**.
3. Click the **⋯** menu (top right) → **Import Blueprint**.
4. Select the corresponding \`.blueprint.json\` file from this folder.
5. Reconnect each module to your live accounts (${companyName}'s CRM, email, etc.).
6. Run the scenario once in **Run once** mode to verify connections.
7. Enable the scenario on your desired schedule or trigger.

## Files in this folder

| File | Purpose |
|------|---------|
| \`*.blueprint.json\` | Customized Make.com scenario blueprints ready to import |
| \`substitutions-audit.json\` | Record of every placeholder replaced during customization |
| \`README.md\` | This file |

## Testing checklist

- Confirm each scenario triggers on a test record (lead, appointment, invoice, etc.).
- Verify emails/SMS arrive from the correct sender and contain ${companyName} branding.
- Check that webhook URLs and API connections respond with HTTP 200.
- Review \`substitutions-audit.json\` to confirm no placeholders were missed.

## Support

For setup assistance, contact Clinovyr at [clinovyr.com](https://clinovyr.com).
`;
}

function writeClientOutput(
  rootDir: string,
  answers: WizardAnswers,
  results: Record<string, CustomizeResult>,
  library: TemplateLibrary
): string {
  const slug = slugifyCompanyName(answers.companyName);
  const outputDir = path.join(rootDir, "customized-for-client", slug);

  fs.mkdirSync(outputDir, { recursive: true });

  const audit: Record<
    string,
    { substitutions: SubstitutionRecord[]; outputFile: string }
  > = {};

  for (const [templateId, result] of Object.entries(results)) {
    const outputFile = `${templateId}.blueprint.json`;
    const filePath = path.join(outputDir, outputFile);

    fs.writeFileSync(filePath, `${JSON.stringify(result.blueprint, null, 2)}\n`, "utf-8");

    audit[templateId] = {
      substitutions: result.substitutions,
      outputFile,
    };
  }

  fs.writeFileSync(
    path.join(outputDir, "substitutions-audit.json"),
    `${JSON.stringify(
      {
        companyName: answers.companyName,
        generatedAt: new Date().toISOString(),
        clientConfig: {
          ...answers,
          apiKeys: Object.fromEntries(
            Object.keys(answers.apiKeys).map((key) => [key, "[REDACTED]"])
          ),
        },
        templates: audit,
      },
      null,
      2
    )}\n`,
    "utf-8"
  );

  fs.writeFileSync(
    path.join(outputDir, "README.md"),
    buildReadme(answers.companyName, answers.templateIds, library),
    "utf-8"
  );

  return outputDir;
}

async function runWizard(): Promise<void> {
  const rootDir = path.resolve(__dirname, "..");
  const library = new TemplateLibrary(rootDir);
  library.loadCatalog();

  const templates = library.listTemplates();
  const rl = createReadlineInterface();

  try {
    console.log("\nClinovyr Make.com Template Setup Wizard\n");
    console.log("Available templates:\n");

    templates.forEach((template, index) => {
      console.log(
        `  ${index + 1}. ${template.id} — ${template.name} [${template.vertical.join(", ")}]`
      );
    });

    console.log(
      "\nSelect templates by number (e.g. 1,3,5) or id (e.g. lead-followup-email,review-request)."
    );

    const selectionInput = await ask(rl, "Templates to customize: ");
    const templateIds = parseTemplateSelection(selectionInput, templates);

    if (templateIds.length === 0) {
      throw new Error("Select at least one template.");
    }

    const companyName = await ask(rl, "Client company name: ");
    if (!companyName) {
      throw new Error("Company name is required.");
    }

    const crmType = await ask(rl, "CRM type (e.g. HubSpot, Salesforce, GoHighLevel): ");
    const emailProvider = await ask(
      rl,
      "Email provider (e.g. Gmail, Outlook, SendGrid): "
    );
    const webhookUrl = await ask(
      rl,
      "Webhook URL (or placeholder https://hooks.example.com/client): "
    );

    const apiKeys = await promptApiKeys(rl);

    const clientConfig: ClientConfig = {
      companyName,
      crmType: crmType || "HubSpot",
      emailProvider: emailProvider || "Gmail",
      webhookUrl: webhookUrl || "https://hooks.example.com/client",
      apiKeys,
    };

    const results: Record<string, CustomizeResult> = {};

    for (const templateId of templateIds) {
      console.log(`\nCustomizing ${templateId}...`);
      results[templateId] = library.customizeTemplate(templateId, clientConfig);
    }

    const outputDir = writeClientOutput(rootDir, {
      templateIds,
      ...clientConfig,
    }, results, library);

    console.log(`\nDone! Client package written to:\n  ${outputDir}\n`);
  } finally {
    rl.close();
  }
}

if (require.main === module) {
  runWizard().catch((error: unknown) => {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`\nWizard failed: ${message}\n`);
    process.exit(1);
  });
}
